name: Create Release
on: 
  push:
    tags:
    - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: 'mmpork.zip'
        exclusions: '*.git*'
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: 'mmpork.zip'
        bodyFile: "README.md"
